<div class="small-2 columns">
	<a href="/syndication/api">
		<img src="/publishedcontent/Images/images/clinicaltrials/search-code.png" class="" alt="Search Code"/>
	</a>
</div>
<div class="small-10 columns">
	<a href="/syndication/api">
		<h3>The Clinical Trials API: Use our data to power your own clinical trial search</h3>
	</a>
	<p>An application programming interface (API) helps translate large amounts of data in meaningful ways. This clinical trials search is now powered by an API to help provide better search results and for developers to use this open data.</p>
</div>
