<h3>The Clinical Trials API: Use our data to power your own clinical trial search</h3>
<div class="api-reference-content">
    <p>An application programming interface (API) helps translate large amounts of data in meaningful ways. NCI’s clinical trials search data is now powered by an API, allowing programmers to build applications <a href="/syndication/api">using this open data.</a></p>
</div>