<div class="row">
<div class="medium-9 columns">
<h3>The Clinical Trials API: Use our data to power your own clinical trial search</h3>	
<div class="api-reference-content clearfix">
<div class="small-2 columns">
	<a href="/syndication/api">
		<img src="/publishedcontent/Images/images/design-elements/icons/api-icon.svg" class="api-section-image" alt="Search Code" />
	</a>
</div>
<div class="small-10 columns">
	<p>An application programming interface (API) helps translate large amounts of data in meaningful ways. NCI’s clinical trials search data is now powered by an API, allowing programmers to build applications <a href="/syndication/api">using this open data.</a></p>
</div>
</div>

</div>
</div>
