<div class="delighter cts-livehelp">
	<h4 id="ui-id-2">Have a question?</h4>
	<p>We're here to help</p><hr>
	<p class="chat-with-us">
		<a href="/contact">Chat with us: <img alt="LiveHelp" src="/publishedcontent/images/images/design-elements/background-graphics/live-help-logo.svg" class="live-help-button"></a>
	</p>
	<p>Call us:
	  <br><span>1-800-4-CANCER</span>
	</p>
	<p><span>(1-800-422-6237)</span></p>
</div>