<link rel="apple-touch-icon" sizes="57x57" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/publishedcontent/images/images/design-elements/icons/favicons/manifest.json">
<link rel="shortcut icon" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Cancer.gov">
<meta name="application-name" content="Cancer.gov">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/publishedcontent/images/images/design-elements/icons/favicons/mstile-144x144.png">
<meta name="msapplication-config" content="/publishedcontent/images/images/design-elements/icons/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
