<link rel="apple-touch-icon" sizes="180x180" href="/publishedcontent/images/images/design-elements/icons/favicons/apple-touch-icon.png?v=oLa52veKe8" />
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon-32x32.png?v=oLa52veKe8" sizes="32x32" />
<link rel="icon" type="image/png" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon-16x16.png?v=oLa52veKe8" sizes="16x16" />
<link rel="manifest" href="/publishedcontent/images/images/design-elements/icons/favicons/manifest.json?v=oLa52veKe8" />
<link rel="mask-icon" href="/publishedcontent/images/images/design-elements/icons/favicons/safari-pinned-tab.svg?v=oLa52veKe8" color="#c0143c" />
<link rel="shortcut icon" href="/publishedcontent/images/images/design-elements/icons/favicons/favicon.ico?v=oLa52veKe8" />
<meta name="apple-mobile-web-app-title" content="Cancer.gov" />
<meta name="application-name" content="Cancer.gov" />
<meta name="msapplication-config" content="/publishedcontent/images/images/design-elements/icons/favicons/browserconfig.xml?v=oLa52veKe8" />
<meta name="theme-color" content="#ffffff" />