<!--(bake-start _if="comment-block")-->
<!--
    This include is the page options for all JS App Module pages.  SInce 3 templates share the same options, this include has been created to make
    life easier if the CSS Classes for the page options needs to change for inner pages.
-->
<!--(bake-end)-->
<!--(bake PageOptions.inc  resize="false" print="false" email="true" facebook="false" twitter="true" pinterest="false")-->
