<!--(bake-start _if="comment-block")-->
<!--
    This include is the page options for CTHP pages, which should not include the "Resize" button.
	Since these templates share the same options, this include has been created to make
    life easier if the CSS Classes for the page options needs to change for inner pages.
-->
<!--(bake-end)-->
<!--(bake PageOptions.inc css-class="page-options no-resize")-->
